version: '3.9'
services:
  db:
    image: mysql:5.7.22
    container_name: dev-mysql
    restart: always
    environment:
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "13306:3306"